<?php


namespace Magenest\Movie\Model\ResourceModel\Movie;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName ='movie_id';
    protected function _construct()
    {
        $this->_init('Magenest\Movie\Model\Movie','Magenest\Movie\Model\ResourceModel\Movie');
        parent::_construct(); // TODO: Change the autogenerated stub
    }
    public function getMovies(){
        $this->addFieldToSelect('*');
        $this->getSelect()
            ->join('magenest_movie_actor','main_table.movie_id=magenest_movie_actor.movie_id')
            ->join('magenest_actor','magenest_actor.actor_id=magenest_movie_actor.actor_id',['actor_name'=>'magenest_actor.name'])
            ->join('magenest_director','main_table.director_id=magenest_director.director_id',array('director_namr'=>'magenest_director.name'));
        $this->getSelect()->group('main_table.movie_id');
        return $this->getData();
    }


}
