<style>
    #notification_viewed{
        background-color: white;
    }
    #notification_not_viewed {
     background-color: pink;
    }
</style>
<div <div class="table-wrapper show-notification">
    <table class="data table show" id="my-notification-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Short Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $result = $block->getMyNotification();?>
            <?php foreach ($result['received'] as $notificationReceived) : ?>
               <?php if (in_array($notificationReceived['entity_id'],$result['seen'])) { ?>
                        <tr id="notification_viewed">
                            <td name="entity_id"><?php echo $notificationReceived['entity_id']?></td>
                            <td name="created_at"><?php echo $notificationReceived['created_at']?></td>
                            <td name="short_description"><?php echo $notificationReceived['short_description']?></td>
                            <td name="action" id="col actions">
                                <div>
                                    <a class="view_detail_change_redirect_url" id="<?php echo $notificationReceived['entity_id']?>" href="https://www.google.com/" target="_blank">
                                        <span>View detail</span>
                                    </a>
                                    <span> | </span>
                                    <a id="<?php echo $notificationReceived['entity_id']?>"  class="delete_notification" href="">
                                        <span>Delete</span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php } else{?>
                    <tr id="notification_not_viewed">
                        <td id="entity_id" name="entity_id"><?php echo $notificationReceived['entity_id']?></td>
                        <td name="created_at"><?php echo $notificationReceived['created_at']?></td>
                        <td name="short_description"><?php echo $notificationReceived['short_description']?></td>
                        <td name="action" id="col actions">
                            <div>
                                <a class="view_detail_change_redirect_url" id="<?php echo $notificationReceived['entity_id']?>" href="https://www.google.com/" target="_blank">
                                    <span>View detail</span>
                                </a>
                                <span> | </span>
                                <a id="<?php echo $notificationReceived['entity_id']?>"  class="mark_as_read" href="" >
                                    <span>Mark as read</span>
                                </a>
                                <span> | </span>
                                <a id="<?php echo $notificationReceived['entity_id']?>"  class="delete_notification" href="">
                                    <span>Delete</span>
                                </a>
                            </div>
                        </td>
                    </tr>
            <?php } ?>
            <?php endforeach;?>
        </tbody>
    </table>
    <div id="total_notification_not_viewed"></div>
</div>
<script>
    require(['changeUrl','changeViewed','deleteNotification'],function (changeUrl,changeViewed,deleteNotification){
        changeUrl();
        changeViewed();
        deleteNotification();
    })
</script>




