<?php


namespace Magenest\Notification\Model\ResourceModel\Notification;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName='entity_id';
    protected function _construct()
    {
        $this->_init('Magenest\Notification\Model\Notification','Magenest\Notification\Model\ResourceModel\Notification');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
