<?php


namespace Magenest\WeddingEvent\Model\ResourceModel\Wedding;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';
    protected function _construct()
    {
        $this->_init('Magenest\WeddingEvent\Model\Wedding','Magenest\WeddingEvent\Model\ResourceModel\Wedding');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
