<div>
    <form>
        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" id="first_name">
        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name" id="last_name">
        <label for="email">Email:</label>
        <input type="text" name="email" id="email">
        <label for="company">Company</label>
        <input type="text" name="company" id="company">
        <label for="phone_number">Phone number:</label>
        <input type="text" name="phone_number" id="phone_number">
        <label for="fax">Fax:</label>
        <input type="text" name="fax" id="fax">
        <label for="address">Address:</label>
        <input type="text" name="address" id="address">
        <label for="street">Street:</label>
        <input type="text" name="street" id="street">
        <label for="country">Country:</label>
        <input type="text" name="country" id="country">
        <label for="city">City:</label>
        <input type="text" name="city" id="city">
        <label for="postcode">Postcode:</label>
        <input type="text" name="postcode" id="postcode">
        <label for="total_sales">Total sales:</label>
        <input type="text" name="total_sales" id="total_sales">
        <input type="submit" value="Show Vendor">
    </form>
</div>
