<style>
    #btn_view_customer_same_prefix {
        margin-top: 10px;
        margin-bottom: 10px;
        background-color: #2ea9ec;
    }
</style>
<button type="submit"  id="btn_view_customer_same_prefix">View customers have same custom prefix</button>


<div id="show_data"></div>

<script>
    require(['showCustomPrefix'],function(showCustomPrefix){
        showCustomPrefix();
    })
</script>


