<div class="container">
    <table class="table table-bordered">
        <thead>
        <tr>
            <td>&nbsp;</td>
            <td colspan="6">
                <div align="center"><strong>Magenest Movies</strong></div>
            </td>
        </tr>
        <tr>
            <td>Order</td>
            <td>Movie name</td>
            <td>Description</td>
            <td>Rating</td>
            <td>Director name</td>
            <td>Actor name</td>
        </tr>
        </thead>
<!--        <tbody>-->
<!--        --><?php //foreach($block->getMovies() as $index=>$movie): ?>
<!--            <tr>-->
<!--                <td class="danger">--><?php //echo $index+1; ?><!--</td>-->
<!--                <td class="danger">--><?php //echo $movie['name']; ?><!--</td>-->
<!--                <td class="danger">--><?php //echo $movie['description']; ?><!--</td>-->
<!--                <td class="danger">--><?php //echo $movie['rating']; ?><!--</td>-->
<!--                <td class="danger">--><?php //echo $movie['director_name']; ?><!--</td>-->
<!--                <td class="danger">-->
<!--                    --><?php
//                    $actors=explode (",", $movie['actor_name']);
//                    echo "<ol>";
//                    foreach($actors as $acIndex=>$actor){
//                        echo "<li>$actor</li>";
//                    }
//                    echo "</ol>"
//                    ?>
<!--                </td>-->
<!---->
<!--                <td></td>-->
<!--            </tr>-->
<!--        --><?//endforeach;?>
<!--        </tbody>-->
    </table>
</div>
